BugFix: When calculating dlrr, precision is lost in integer operations, errors occur in rtt calculations.
pion/interceptor pull request #175
Opened 2023-02-15 06:35 UTC by r1a2y3

#### Description
 `time.Duration(xrReport.DLRR/65536.0)`  
 This will cause precision lost. for example, when xrReport.DLRR=30000, result 0 is unexpected. 
 Following the method just like dlsr
`dlsr := time.Duration(float64(report.Delay) / 65536.0 * float64(time.Second))`

2023-02-15 06:51 UTC, ashellunts commented
Hi @r1a2y3 . Thank you for your PR. Would you mind add a unit test for the bug fix? It will ensure the bug never won't come back.

Also please check linter failure.

2023-02-15 06:52 UTC, ashellunts requested changes
Hi @r1a2y3 . Thank you for your PR. Would you mind add a unit test for the bug fix? It will ensure the bug never won't come back.

Also please check linter failure.

2023-02-15 07:26 UTC, stv0g commented
@r1a2y3 Cool :) Thanks for the fix. Please also check the failed CI stage and correct your commit message:

https://github.com/pion/interceptor/actions/runs/4181263561/jobs/7243148213

2023-02-16 02:03 UTC, r1a2y3 commented
thanks @stv0g  @ashellunts , I will try it in a few days. I need learn more about how to do that because this is my first time to create PR in github.

2023-02-22 07:36 UTC, stv0g commented
Hi @r1a2y3,

It should be relatively easiy to fix the commit message:

```bash
git commit --amend
<change your commit message in the opening editor>
git push -f
```

2023-04-25 03:25 UTC, Sean-Der commented
Thank you so much for the PR @r1a2y3 

I added a unit test and fixed the commit message. I hope you stay involved in the project. If you have any feedback/suggestions/improvements we are always looking to get better :)

2023-04-25 03:25 UTC, merged